DROP DATABASE IF EXISTS dailyRhythm;

CREATE DATABASE dailyRhythm;


CREATE TABLE taskMain
ID INTEGER PRIMARY KEY AUTOINCREMENT,
task_name VARCHAR(255) NOT NULL,
task_description VARCHAR(255) NOT NULL,


CREATE TABLE chores
ID INTEGER PRIMARY KEY AUTOINCREMENT,
chore_name VARCHAR(255) NOT NULL,
chore_description VARCHAR(255) NOT NULL,
